"""initial relational schema

Revision ID: 194ef745e4c1
Revises:
Create Date: 2026-08-01 18:28:30.407164
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.db.types import VectorStorage

revision: str = "194ef745e4c1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    op.create_table(
        "episodic",
        sa.Column("episodic_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("kind_fixed_from", sa.String(length=32), nullable=True),
        sa.Column("kind_fixed_at", sa.String(length=32), nullable=True),
        sa.Column("summary_1line", sa.String(length=256), nullable=False),
        sa.Column("emotion", sa.String(length=8), nullable=False),
        sa.Column("entities_json", sa.JSON(), nullable=False),
        sa.Column("raw_user_text", sa.Text(), nullable=False),
        sa.Column("raw_assistant_text", sa.Text(), nullable=True),
        sa.Column("media_json", sa.JSON(), nullable=True),
        sa.Column("retrieval_weight", sa.Float(), nullable=False),
        sa.Column("last_landed_at", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("ref_ledger_ids_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("episodic_id"),
    )
    with op.batch_alter_table("episodic", schema=None) as batch_op:
        batch_op.create_index("idx_ep_user_date", ["user_id", "created_at"], unique=False)
        batch_op.create_index("idx_ep_user_kind", ["user_id", "kind", "created_at"], unique=False)
        batch_op.create_index("idx_ep_user_weight", ["user_id", "retrieval_weight"], unique=False)
        batch_op.create_index(batch_op.f("ix_episodic_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_episodic_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_episodic_retrieval_weight"), ["retrieval_weight"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_episodic_user_id"), ["user_id"], unique=False)

    op.create_table(
        "graph_edges",
        sa.Column("src", sa.String(length=64), nullable=False),
        sa.Column("dst", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("src", "dst", "user_id"),
    )
    op.create_table(
        "graph_nodes",
        sa.Column("node_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("node_type", sa.String(length=32), nullable=False),
        sa.Column("node_name", sa.String(length=128), nullable=False),
        sa.Column("entity_norm_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("node_id", "user_id"),
    )
    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_graph_nodes_entity_norm_name"), ["entity_norm_name"], unique=False
        )

    op.create_table(
        "insights",
        sa.Column("insight_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("text_html", sa.Text(), nullable=False),
        sa.Column("meta", sa.String(length=128), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("feedback_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("ref_semantic_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("insight_id"),
    )
    with op.batch_alter_table("insights", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_insights_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_insights_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_insights_type"), ["type"], unique=False)
        batch_op.create_index(batch_op.f("ix_insights_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memory_deletion_tombstones",
        sa.Column("tombstone_id", sa.String(length=36), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=False),
        sa.Column("resource_hash", sa.String(length=64), nullable=False),
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("completed_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("tombstone_id"),
    )
    with op.batch_alter_table("memory_deletion_tombstones", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memory_deletion_tombstones_completed_at"), ["completed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_deletion_tombstones_resource_hash"),
            ["resource_hash"],
            unique=True,
        )

    op.create_table(
        "memos",
        sa.Column("memo_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("clean_text", sa.Text(), nullable=False),
        sa.Column("due_text", sa.String(length=128), nullable=False),
        sa.Column("due_iso", sa.String(length=32), nullable=True),
        sa.Column("due_offset_days", sa.Integer(), nullable=False),
        sa.Column("importance", sa.String(length=8), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("notified_ios_ids_json", sa.JSON(), nullable=True),
        sa.Column("status_changed_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("linked_episodic_id", sa.String(length=36), nullable=True),
        sa.Column("linked_ledger_id", sa.String(length=36), nullable=True),
        sa.Column("detect_meta_json", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("memo_id"),
    )
    with op.batch_alter_table("memos", schema=None) as batch_op:
        batch_op.create_index("idx_memo_due_iso", ["due_iso"], unique=False)
        batch_op.create_index(
            "idx_memo_user_imp", ["user_id", "importance", "status"], unique=False
        )
        batch_op.create_index(
            "idx_memo_user_status",
            ["user_id", "status", "due_offset_days", "created_at"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_memos_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_memos_due_iso"), ["due_iso"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memos_due_offset_days"), ["due_offset_days"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memos_importance"), ["importance"], unique=False)
        batch_op.create_index(batch_op.f("ix_memos_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_memos_user_id"), ["user_id"], unique=False)

    op.create_table(
        "outbox_events",
        sa.Column("outbox_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("aggregate_type", sa.String(length=32), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.String(length=32), nullable=False),
        sa.Column("locked_at", sa.String(length=32), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("processed_at", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("outbox_id"),
    )
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_outbox_dispatch", ["status", "available_at", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_aggregate_id"), ["aggregate_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_aggregate_type"), ["aggregate_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_available_at"), ["available_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outbox_events_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "procedural",
        sa.Column("proc_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("param_key", sa.String(length=64), nullable=False),
        sa.Column("param_value_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("learned_reason", sa.Text(), nullable=False),
        sa.Column("learned_ev_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.Column("ref_ledger_ids_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("proc_id"),
        sa.UniqueConstraint("user_id", "param_key", name="uq_proc_user_key"),
    )
    op.create_table(
        "raw_ledger",
        sa.Column("ledger_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("entry_type", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("ref_ledger_id", sa.String(length=36), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("trace_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("ledger_id"),
    )
    with op.batch_alter_table("raw_ledger", schema=None) as batch_op:
        batch_op.create_index("idx_ledger_type_time", ["entry_type", "created_at"], unique=False)
        batch_op.create_index("idx_ledger_user_session", ["user_id", "session_id"], unique=False)
        batch_op.create_index("idx_ledger_user_time", ["user_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_ledger_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_ledger_entry_type"), ["entry_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_ledger_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_ledger_user_id"), ["user_id"], unique=False)

    op.create_table(
        "semantic",
        sa.Column("semantic_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("fact_text", sa.Text(), nullable=False),
        sa.Column("source_kind", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("retrieval_weight", sa.Float(), nullable=False),
        sa.Column("last_landed_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("semantic_id"),
    )
    with op.batch_alter_table("semantic", schema=None) as batch_op:
        batch_op.create_index("idx_sem_user_cat", ["user_id", "category", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_semantic_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_semantic_retrieval_weight"), ["retrieval_weight"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_semantic_user_id"), ["user_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("locale", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=32), nullable=False),
        sa.Column("dashscope_quota", sa.Integer(), nullable=False),
        sa.Column("current_style", sa.String(length=32), nullable=False),
        sa.Column("settings_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "working",
        sa.Column("working_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mood", sa.String(length=8), nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("ref_ledger_id", sa.String(length=36), nullable=True),
        sa.PrimaryKeyConstraint("working_id"),
    )
    with op.batch_alter_table("working", schema=None) as batch_op:
        batch_op.create_index(
            "idx_wkg_user_session", ["user_id", "session_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_working_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_working_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memory_claims",
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("claim_type", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=128), nullable=False),
        sa.Column("predicate", sa.String(length=128), nullable=False),
        sa.Column("object_value", sa.Text(), nullable=False),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("slot_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("user_status", sa.String(length=24), nullable=False),
        sa.Column("sensitivity", sa.String(length=16), nullable=False),
        sa.Column("valid_from", sa.String(length=32), nullable=True),
        sa.Column("valid_to", sa.String(length=32), nullable=True),
        sa.Column("observed_at", sa.String(length=32), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("supersedes_claim_id", sa.String(length=36), nullable=True),
        sa.Column("pinned", sa.Boolean(), nullable=False),
        sa.Column("allow_proactive", sa.Boolean(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("last_landed_at", sa.String(length=32), nullable=True),
        sa.Column("retrieval_count", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_policy_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.Column("deleted_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["supersedes_claim_id"], ["memory_claims.claim_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id"),
    )
    with op.batch_alter_table("memory_claims", schema=None) as batch_op:
        batch_op.create_index(
            "idx_memory_claim_retrievable",
            ["user_id", "user_status", "valid_to", "pinned"],
            unique=False,
        )
        batch_op.create_index(
            "idx_memory_claim_user_slot", ["user_id", "slot_key", "user_status"], unique=False
        )
        batch_op.create_index(
            "idx_memory_claim_user_updated", ["user_id", "updated_at", "claim_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_claims_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_claims_claim_type"), ["claim_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_claims_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_claims_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_claims_pinned"), ["pinned"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_claims_sensitivity"), ["sensitivity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_claims_slot_key"), ["slot_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_claims_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_claims_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_claims_user_status"), ["user_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_claims_valid_from"), ["valid_from"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_claims_valid_to"), ["valid_to"], unique=False)

    op.create_table(
        "memory_retrieval_traces",
        sa.Column("trace_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("query_hash", sa.String(length=64), nullable=False),
        sa.Column("route", sa.String(length=32), nullable=False),
        sa.Column("candidates_json", sa.JSON(), nullable=False),
        sa.Column("selected_json", sa.JSON(), nullable=False),
        sa.Column("used_in_response", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trace_id"),
    )
    with op.batch_alter_table("memory_retrieval_traces", schema=None) as batch_op:
        batch_op.create_index(
            "idx_memory_trace_user_time", ["user_id", "created_at", "trace_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_retrieval_traces_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_retrieval_traces_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_retrieval_traces_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("client_event_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.String(length=32), nullable=False),
        sa.Column("recorded_at", sa.String(length=32), nullable=False),
        sa.Column("sensitivity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("source_ref_id", sa.String(length=36), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("deleted_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("user_id", "client_event_id", name="uq_user_events_user_client_event"),
        sa.UniqueConstraint("user_id", "request_id", name="uq_user_events_user_request"),
    )
    with op.batch_alter_table("user_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_user_events_user_time", ["user_id", "occurred_at", "event_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_events_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_events_mode"), ["mode"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_events_recorded_at"), ["recorded_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_events_sensitivity"), ["sensitivity"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_events_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_events_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_events_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memory_embeddings",
        sa.Column("embedding_id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("vector_json", VectorStorage(dimension=1024), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["memory_claims.claim_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("embedding_id"),
        sa.UniqueConstraint(
            "claim_id", "model", "content_hash", name="uq_memory_embedding_version"
        ),
    )
    with op.batch_alter_table("memory_embeddings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_memory_embeddings_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_embeddings_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_embeddings_user_id"), ["user_id"], unique=False)

    if op.get_bind().dialect.name == "postgresql":
        op.create_index(
            "idx_memory_embeddings_vector_hnsw",
            "memory_embeddings",
            ["vector_json"],
            unique=False,
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"vector_json": "vector_cosine_ops"},
        )

    op.create_table(
        "memory_evidence",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_role", sa.String(length=16), nullable=False),
        sa.Column("excerpt_start", sa.Integer(), nullable=False),
        sa.Column("excerpt_end", sa.Integer(), nullable=False),
        sa.Column("excerpt_text", sa.Text(), nullable=False),
        sa.Column("source_weight", sa.Float(), nullable=False),
        sa.Column("extractor_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["memory_claims.claim_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["user_events.event_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evidence_id"),
        sa.UniqueConstraint(
            "claim_id", "event_id", "evidence_role", name="uq_memory_evidence_once"
        ),
    )
    with op.batch_alter_table("memory_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "idx_memory_evidence_claim_time", ["claim_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_evidence_claim_id"), ["claim_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_evidence_event_id"), ["event_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_evidence_evidence_role"), ["evidence_role"], unique=False
        )

    op.create_table(
        "memory_relations",
        sa.Column("relation_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("src_type", sa.String(length=24), nullable=False),
        sa.Column("src_id", sa.String(length=128), nullable=False),
        sa.Column("dst_type", sa.String(length=24), nullable=False),
        sa.Column("dst_id", sa.String(length=128), nullable=False),
        sa.Column("relation_type", sa.String(length=48), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.String(length=32), nullable=True),
        sa.Column("valid_to", sa.String(length=32), nullable=True),
        sa.Column("source_event_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["source_event_id"], ["user_events.event_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("relation_id"),
    )
    with op.batch_alter_table("memory_relations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_memory_relation_user_dst",
            ["user_id", "dst_type", "dst_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            "idx_memory_relation_user_src",
            ["user_id", "src_type", "src_id", "status"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_memory_relations_dst_id"), ["dst_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_relations_relation_type"), ["relation_type"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_memory_relations_src_id"), ["src_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_relations_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_memory_relations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "memory_revisions",
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("claim_id", sa.String(length=36), nullable=False),
        sa.Column("actor_type", sa.String(length=24), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("before_json", sa.JSON(), nullable=False),
        sa.Column("after_json", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["claim_id"], ["memory_claims.claim_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("revision_id"),
    )
    with op.batch_alter_table("memory_revisions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_revisions_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_memory_revisions_claim_id"), ["claim_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_memory_revisions_created_at"), ["created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("memory_revisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_revisions_created_at"))
        batch_op.drop_index(batch_op.f("ix_memory_revisions_claim_id"))
        batch_op.drop_index(batch_op.f("ix_memory_revisions_action"))

    op.drop_table("memory_revisions")
    with op.batch_alter_table("memory_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_relations_user_id"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_status"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_src_id"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_relation_type"))
        batch_op.drop_index(batch_op.f("ix_memory_relations_dst_id"))
        batch_op.drop_index("idx_memory_relation_user_src")
        batch_op.drop_index("idx_memory_relation_user_dst")

    op.drop_table("memory_relations")
    with op.batch_alter_table("memory_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_evidence_evidence_role"))
        batch_op.drop_index(batch_op.f("ix_memory_evidence_event_id"))
        batch_op.drop_index(batch_op.f("ix_memory_evidence_claim_id"))
        batch_op.drop_index("idx_memory_evidence_claim_time")

    op.drop_table("memory_evidence")
    if op.get_bind().dialect.name == "postgresql":
        op.drop_index(
            "idx_memory_embeddings_vector_hnsw",
            table_name="memory_embeddings",
        )

    with op.batch_alter_table("memory_embeddings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_embeddings_user_id"))
        batch_op.drop_index(batch_op.f("ix_memory_embeddings_status"))
        batch_op.drop_index(batch_op.f("ix_memory_embeddings_claim_id"))

    op.drop_table("memory_embeddings")
    with op.batch_alter_table("user_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_events_status"))
        batch_op.drop_index(batch_op.f("ix_user_events_session_id"))
        batch_op.drop_index(batch_op.f("ix_user_events_sensitivity"))
        batch_op.drop_index(batch_op.f("ix_user_events_recorded_at"))
        batch_op.drop_index(batch_op.f("ix_user_events_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_user_events_mode"))
        batch_op.drop_index(batch_op.f("ix_user_events_content_hash"))
        batch_op.drop_index("idx_user_events_user_time")

    op.drop_table("user_events")
    with op.batch_alter_table("memory_retrieval_traces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_retrieval_traces_user_id"))
        batch_op.drop_index(batch_op.f("ix_memory_retrieval_traces_request_id"))
        batch_op.drop_index(batch_op.f("ix_memory_retrieval_traces_created_at"))
        batch_op.drop_index("idx_memory_trace_user_time")

    op.drop_table("memory_retrieval_traces")
    with op.batch_alter_table("memory_claims", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_claims_valid_to"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_valid_from"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_user_status"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_user_id"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_updated_at"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_slot_key"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_sensitivity"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_pinned"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_created_at"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_content_hash"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_claim_type"))
        batch_op.drop_index(batch_op.f("ix_memory_claims_category"))
        batch_op.drop_index("idx_memory_claim_user_updated")
        batch_op.drop_index("idx_memory_claim_user_slot")
        batch_op.drop_index("idx_memory_claim_retrievable")

    op.drop_table("memory_claims")
    with op.batch_alter_table("working", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_working_user_id"))
        batch_op.drop_index(batch_op.f("ix_working_session_id"))
        batch_op.drop_index("idx_wkg_user_session")

    op.drop_table("working")
    op.drop_table("users")
    with op.batch_alter_table("semantic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_semantic_user_id"))
        batch_op.drop_index(batch_op.f("ix_semantic_retrieval_weight"))
        batch_op.drop_index(batch_op.f("ix_semantic_category"))
        batch_op.drop_index("idx_sem_user_cat")

    op.drop_table("semantic")
    with op.batch_alter_table("raw_ledger", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_ledger_user_id"))
        batch_op.drop_index(batch_op.f("ix_raw_ledger_session_id"))
        batch_op.drop_index(batch_op.f("ix_raw_ledger_entry_type"))
        batch_op.drop_index(batch_op.f("ix_raw_ledger_created_at"))
        batch_op.drop_index("idx_ledger_user_time")
        batch_op.drop_index("idx_ledger_user_session")
        batch_op.drop_index("idx_ledger_type_time")

    op.drop_table("raw_ledger")
    op.drop_table("procedural")
    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_status"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_available_at"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_aggregate_type"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_aggregate_id"))
        batch_op.drop_index("idx_outbox_dispatch")

    op.drop_table("outbox_events")
    with op.batch_alter_table("memos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memos_user_id"))
        batch_op.drop_index(batch_op.f("ix_memos_status"))
        batch_op.drop_index(batch_op.f("ix_memos_importance"))
        batch_op.drop_index(batch_op.f("ix_memos_due_offset_days"))
        batch_op.drop_index(batch_op.f("ix_memos_due_iso"))
        batch_op.drop_index(batch_op.f("ix_memos_created_at"))
        batch_op.drop_index("idx_memo_user_status")
        batch_op.drop_index("idx_memo_user_imp")
        batch_op.drop_index("idx_memo_due_iso")

    op.drop_table("memos")
    with op.batch_alter_table("memory_deletion_tombstones", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_deletion_tombstones_resource_hash"))
        batch_op.drop_index(batch_op.f("ix_memory_deletion_tombstones_completed_at"))

    op.drop_table("memory_deletion_tombstones")
    with op.batch_alter_table("insights", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_insights_user_id"))
        batch_op.drop_index(batch_op.f("ix_insights_type"))
        batch_op.drop_index(batch_op.f("ix_insights_status"))
        batch_op.drop_index(batch_op.f("ix_insights_created_at"))

    op.drop_table("insights")
    with op.batch_alter_table("graph_nodes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_graph_nodes_entity_norm_name"))

    op.drop_table("graph_nodes")
    op.drop_table("graph_edges")
    with op.batch_alter_table("episodic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episodic_user_id"))
        batch_op.drop_index(batch_op.f("ix_episodic_retrieval_weight"))
        batch_op.drop_index(batch_op.f("ix_episodic_kind"))
        batch_op.drop_index(batch_op.f("ix_episodic_created_at"))
        batch_op.drop_index("idx_ep_user_weight")
        batch_op.drop_index("idx_ep_user_kind")
        batch_op.drop_index("idx_ep_user_date")

    op.drop_table("episodic")
    # ### end Alembic commands ###
