"""add identity sessions and admin rbac

Revision ID: 8ce4cecf534e
Revises: 194ef745e4c1
Create Date: 2026-08-01 19:26:05.388553
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8ce4cecf534e"
down_revision: str | Sequence[str] | None = "194ef745e4c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_events",
        sa.Column("audit_id", sa.String(length=36), nullable=False),
        sa.Column("actor_admin_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=96), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("source_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent_hash", sa.String(length=64), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    with op.batch_alter_table("admin_audit_events", schema=None) as batch_op:
        batch_op.create_index(
            "idx_admin_audit_time_action", ["created_at", "action", "outcome"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_admin_audit_events_action"), ["action"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_admin_audit_events_actor_admin_id"), ["actor_admin_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_events_outcome"), ["outcome"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_events_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_admin_audit_events_resource_type"), ["resource_type"], unique=False
        )

    op.create_table(
        "admin_permissions",
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("permission_code"),
    )
    op.create_table(
        "admin_roles",
        sa.Column("role_code", sa.String(length=48), nullable=False),
        sa.Column("display_name", sa.String(length=96), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("role_code"),
    )
    op.create_table(
        "admin_users",
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("username_normalized", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("totp_secret_ciphertext", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until_epoch", sa.Integer(), nullable=True),
        sa.Column("last_totp_step", sa.Integer(), nullable=True),
        sa.Column("password_changed_at", sa.String(length=32), nullable=False),
        sa.Column("last_login_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("admin_id"),
        sa.UniqueConstraint("username_normalized"),
    )
    with op.batch_alter_table("admin_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admin_users_status"), ["status"], unique=False)

    op.create_table(
        "auth_challenges",
        sa.Column("challenge_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at_epoch", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.String(length=32), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("challenge_id"),
        sa.UniqueConstraint("nonce_hash"),
    )
    with op.batch_alter_table("auth_challenges", schema=None) as batch_op:
        batch_op.create_index(
            "idx_auth_challenge_dispatch", ["provider", "status", "expires_at_epoch"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_auth_challenges_expires_at_epoch"), ["expires_at_epoch"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_auth_challenges_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_challenges_status"), ["status"], unique=False)

    op.create_table(
        "admin_role_permissions",
        sa.Column("role_code", sa.String(length=48), nullable=False),
        sa.Column("permission_code", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_code"], ["admin_permissions.permission_code"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["role_code"], ["admin_roles.role_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_code", "permission_code"),
    )
    op.create_table(
        "admin_sessions",
        sa.Column("admin_session_id", sa.String(length=36), nullable=False),
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at_epoch", sa.Integer(), nullable=False),
        sa.Column("mfa_verified", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at_epoch", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.String(length=32), nullable=True),
        sa.Column("revoke_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["admin_id"], ["admin_users.admin_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("admin_session_id"),
        sa.UniqueConstraint("access_token_hash"),
    )
    with op.batch_alter_table("admin_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_admin_session_principal", ["admin_id", "status", "expires_at_epoch"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_admin_sessions_admin_id"), ["admin_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_admin_sessions_expires_at_epoch"), ["expires_at_epoch"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_admin_sessions_status"), ["status"], unique=False)

    op.create_table(
        "admin_user_roles",
        sa.Column("admin_id", sa.String(length=36), nullable=False),
        sa.Column("role_code", sa.String(length=48), nullable=False),
        sa.Column("assigned_by_admin_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["admin_id"], ["admin_users.admin_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_code"], ["admin_roles.role_code"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("admin_id", "role_code"),
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("installation_id_hash", sa.String(length=64), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("device_name", sa.String(length=80), nullable=False),
        sa.Column("app_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
        sa.UniqueConstraint("user_id", "installation_id_hash", name="uq_device_user_installation"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(
            "idx_device_user_status", ["user_id", "status", "last_seen_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_devices_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_devices_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_identities",
        sa.Column("identity_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=24), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("email_ciphertext", sa.Text(), nullable=True),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("provider_metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("identity_id"),
        sa.UniqueConstraint("provider", "subject", name="uq_user_identity_provider_subject"),
    )
    with op.batch_alter_table("user_identities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_identities_email_hash"), ["email_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_identities_user_id"), ["user_id"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("access_expires_at_epoch", sa.Integer(), nullable=False),
        sa.Column("refresh_family_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("last_seen_at_epoch", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.String(length=32), nullable=True),
        sa.Column("revoke_reason", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["device_id"], ["devices.device_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
        sa.UniqueConstraint("access_token_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_session_user_status", ["user_id", "status", "last_seen_at_epoch"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sessions_access_expires_at_epoch"),
            ["access_expires_at_epoch"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_sessions_device_id"), ["device_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sessions_refresh_family_id"), ["refresh_family_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_sessions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "refresh_tokens",
        sa.Column("refresh_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("family_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("parent_refresh_id", sa.String(length=36), nullable=True),
        sa.Column("replaced_by_refresh_id", sa.String(length=36), nullable=True),
        sa.Column("expires_at_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(length=32), nullable=False),
        sa.Column("consumed_at", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_refresh_id"], ["refresh_tokens.refresh_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_refresh_id"], ["refresh_tokens.refresh_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.session_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("refresh_id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(
            "idx_refresh_family_status", ["family_id", "status", "expires_at_epoch"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_expires_at_epoch"), ["expires_at_epoch"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_family_id"), ["family_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_refresh_tokens_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_refresh_tokens_status"), ["status"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.String(length=32), nullable=True))
        batch_op.add_column(
            sa.Column("status", sa.String(length=16), server_default="active", nullable=False)
        )
        batch_op.add_column(sa.Column("deleted_at", sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_status"), ["status"], unique=False)

    op.execute(sa.text("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL"))
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("updated_at", existing_type=sa.String(length=32), nullable=False)
        batch_op.alter_column(
            "status", existing_type=sa.String(length=16), server_default=None, nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_status"))
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("status")
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_status"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_session_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_family_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_expires_at_epoch"))
        batch_op.drop_index("idx_refresh_family_status")

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_sessions_refresh_family_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_device_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_access_expires_at_epoch"))
        batch_op.drop_index("idx_session_user_status")

    op.drop_table("sessions")
    with op.batch_alter_table("user_identities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_identities_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_identities_email_hash"))

    op.drop_table("user_identities")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_user_id"))
        batch_op.drop_index(batch_op.f("ix_devices_status"))
        batch_op.drop_index("idx_device_user_status")

    op.drop_table("devices")
    op.drop_table("admin_user_roles")
    with op.batch_alter_table("admin_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_admin_sessions_expires_at_epoch"))
        batch_op.drop_index(batch_op.f("ix_admin_sessions_admin_id"))
        batch_op.drop_index("idx_admin_session_principal")

    op.drop_table("admin_sessions")
    op.drop_table("admin_role_permissions")
    with op.batch_alter_table("auth_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_challenges_status"))
        batch_op.drop_index(batch_op.f("ix_auth_challenges_provider"))
        batch_op.drop_index(batch_op.f("ix_auth_challenges_expires_at_epoch"))
        batch_op.drop_index("idx_auth_challenge_dispatch")

    op.drop_table("auth_challenges")
    with op.batch_alter_table("admin_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_users_status"))

    op.drop_table("admin_users")
    op.drop_table("admin_roles")
    op.drop_table("admin_permissions")
    with op.batch_alter_table("admin_audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admin_audit_events_resource_type"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_events_request_id"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_events_outcome"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_events_actor_admin_id"))
        batch_op.drop_index(batch_op.f("ix_admin_audit_events_action"))
        batch_op.drop_index("idx_admin_audit_time_action")

    op.drop_table("admin_audit_events")
    # ### end Alembic commands ###
